import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#131313",
        "on-background": "#e5e2e1",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#bbcabf",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#86948a",
        "outline-variant": "#3c4a42",
        "surface-tint": "#4edea3",
        primary: {
          DEFAULT: "#4edea3",
          container: "#10b981",
          dim: "#4edea3",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
        },
        secondary: {
          DEFAULT: "#adc6ff",
          container: "#0566d9",
          "fixed-dim": "#adc6ff",
        },
        tertiary: {
          DEFAULT: "#c6c7c0",
          container: "#a2a39c",
        },
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
        },
        "momentum-emerald": "#10b981",
        "warm-ivory": "#f8f8f0",
        "muted-gray": "#71717a",
        "graphite-stroke": "#2a2a2a",
        "terminal-bg": "#131313",
        "surface-raised": "#1c1b1b",
        "chart-blue": "#3b82f6",
        "chart-indigo": "#6366f1",
        "chart-slate": "#475569",
      },
      fontFamily: {
        sans: ["'Hanken Grotesk'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      borderRadius: {
        sm: "2px",
        DEFAULT: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        gutter: "12px",
        "margin-safe": "16px",
        "rail-width": "64px",
      },
    },
  },
  plugins: [],
};
export default config;
